version: "3.7"

services:
  django_socialmediacomposer:
    build: ./backend
    container_name: django_socialmediacomposer
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres_socialmediacomposer
  postgres_socialmediacomposer:
    image: postgres:11.8-alpine
    container_name: postgres_socialmediacomposer
    volumes:
      - postgres_data_socialmediacomposer:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data_socialmediacomposer: