version: "3.7"

services:
  django_socialmediacomposer:
    build: ./backend
    container_name: django_socialmediacomposer
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    dockerfile: Dockerfile.prod
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres_socialmediacomposer

  postgres_socialmediacomposer:
    image: postgres:11.8-alpine
    container_name: postgres_socialmediacomposer
    volumes:
      - postgres_data_socialmediacomposer:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
        - 1337:80
    depends_on:
        - django_socialmediacomposer
volumes:
  postgres_data_socialmediacomposer:
  static_volume:
  media_volume:    